import gzip
from datetime import datetime
from pathlib import Path
from shutil import rmtree
from subprocess import DEVNULL, run
from sys import exit, stderr
from uuid import uuid4


class Checkm2:
    def __init__(self, checkm2, threads, temp):
        self.checkm2 = checkm2
        self.threads = threads
        self.temp = Path(temp)
        return None

    def parseInputFiles(self, files):
        temp = self.temp.joinpath(uuid4().hex)
        temp.mkdir()
        for i in files:
            path = Path(i)
            temp.joinpath(f'{path.stem}.fasta').symlink_to(path.absolute())
        return temp

    def predict(self, inputFiles, outputFile):
        temp1 = self.parseInputFiles(inputFiles)
        temp2 = self.temp.joinpath(uuid4().hex)
        completedProcess = run(
            [self.checkm2, 'predict', '--remove_intermediates', '--force', '-x', 'fasta', '--threads', str(self.threads), '--input', str(temp1), '--output-directory', str(temp2)],
            stdout = DEVNULL, stderr = None
        )
        if completedProcess.returncode:
            print(f'{datetime.now().strftime("%Y-%m-%d %H:%M:%S")} Error: Failed to run CheckM2.', file = stderr, flush = True)
            exit(1)
        rmtree(str(temp1))
        temp2.joinpath('quality_report.tsv').rename(outputFile)
        rmtree(str(temp2))
        return self


def isGzipped(file):
    openFile = open(file, 'rb')
    magicCode = openFile.read(2)
    openFile.close()
    return magicCode == b'\x1f\x8b'


def readCheckm2File(file, contamination, completeness):
    contamination *= 100.0
    completeness *= 100.0
    clusters = list()
    if isGzipped(file):
        openFile = gzip.open(file, mode = 'rt')
    else:
        openFile = open(file, 'r')
    if not openFile.readline().startswith('Name\tCompleteness\tContamination'):
        print(f'{datetime.now().strftime("%Y-%m-%d %H:%M:%S")} Error: \"{file}\" is not a valid output generated by CheckM2.', file = stderr, flush = True)
        exit(1)
    for line in openFile:
        lines = line.rstrip('\n').split('\t', maxsplit = 3)
        if float(lines[1]) >= completeness and float(lines[2]) <= contamination:
            clusters.append(lines[0])
    openFile.close()
    return set(clusters)


def main(parameters):
    checkm2 = Checkm2(parameters.checkm2, parameters.threads, parameters.temp)
    checkm2.predict(parameters.fasta, parameters.output)
    return None
