import gzip
from pathlib import Path
from shutil import rmtree
from subprocess import DEVNULL, run
from uuid import uuid4


def isGzipped(file):
    openFile = open(file, 'rb')
    magicCode = openFile.read(2)
    openFile.close()
    return magicCode == b'\x1f\x8b'


def readCheckm2File(file, contamination, completeness):
    contamination *= 100.0
    completeness *= 100.0
    clusters = list()
    if isGzipped(file):
        openFile = gzip.open(file, mode = 'rt')
    else:
        openFile = open(file, 'r')
    assert openFile.readline().startswith('Name\tCompleteness\tContamination'), f'\"{file}\" is not a valid output generated by CheckM2.'
    for line in openFile:
        lines = line.rstrip('\n').split('\t', maxsplit = 3)
        if float(lines[1]) >= completeness and float(lines[2]) <= contamination:
            clusters.append(lines[0])
    openFile.close()
    return set(clusters)


def runCheckm2(checkm2, threads, inputFiles, outputFile):
    inputDirectory = uuid4().hex
    inputDirectoryPath = Path(inputDirectory)
    inputDirectoryPath.mkdir()
    for inputFile in inputFiles:
        inputFilePath = Path(inputFile)
        inputDirectoryPath.joinpath(f'{inputFilePath.stem}.fasta').symlink_to(inputFilePath.absolute())

    outputDirectory = uuid4().hex
    outputDirectoryPath = Path(outputDirectory)
    completedProcess = run(
        [checkm2, 'predict', '--remove_intermediates', '--force', '-x', 'fasta', '--threads', str(threads), '--input', inputDirectory, '--output-directory', outputDirectory],
        stdout = DEVNULL, stderr = None
    )
    assert not completedProcess.returncode, 'An error has occurred while running CheckM2.'
    rmtree(inputDirectory)
    outputDirectoryPath.joinpath('quality_report.tsv').rename(outputFile)
    rmtree(outputDirectory)
    return None


def main(parameters):
    runCheckm2(parameters.checkm2, parameters.threads, parameters.fasta, parameters.output)
    return None
